bounding_boxes:
  side_on:
    bottom_right:
      x: 1049
      y: 446
    top_left:
      x: 1024
      y: 430
  top_down:
    bottom_right:
      x: 2700
      y: 951
    top_left:
      x: 766
      y: 440
raw_output:
  folder: output_folder
  save_csv: true
  save_excel: false
  save_json: false
