bounding_boxes:
  side_on:
    bottom_right:
      x: 1601
      y: 982
    top_left:
      x: 1566
      y: 933
  top_down:
    bottom_right:
      x: 3835
      y: 1597
    top_left:
      x: 0
      y: 429
raw_output:
  folder: output_folder
  save_csv: true
  save_excel: false
  save_json: false
