bounding_boxes:
  side_on:
    bottom_right:
      x: 2596
      y: 1535
    top_left:
      x: 1614
      y: 637
  top_down:
    bottom_right:
      x: 2592
      y: 2155
    top_left:
      x: 1238
      y: 0
raw_output:
  folder: output_folder
  save_csv: true
  save_excel: false
  save_json: false
